### ISSUE TITLE
How to programatically close a Dialog without index

### ISSUE THREAD

**Issue by folamy** [gitart-group/vue-dialog#1]
I want to close plugin dialog without any click event. dialog.removeDialog() does work without and index!

**Comment by MichaelGitArt** [comment]
Hi, sorry for the long response. It depends on how you opened your dialog.

If you use standalone dialog, you can close by scoped function:
<img width="775" alt="image" src="https://user-images.githubusercontent.com/34610289/182803374-12e12869-8773-4691-b57b-1ebcf8b5b8f3.png">

If you use plugin and GDialogRoot, you should emit this: `emit('update:modelValue', false)`.
<img width="727" alt="image" src="https://user-images.githubusercontent.com/34610289/182804016-bee35b4b-99d6-4491-bfaf-2a3b016840e0.png">

Here is an example in the docs:
https://gitart-vue-dialog.gitart.org/guide/usage/plugin-usage.html#example

**Comment by MichaelGitArt** [comment]
To close all dialogs by the plugin:

$dialog.dialogs.splice(0, $dialog.dialogs.length)
