### ISSUE TITLE
how to get custom emit on a dynamic dialog

### ISSUE THREAD

**Issue by moh586** [gitart-group/vue-dialog#2]
Hi
I created a Component and It is work well, but I couldn't get my emit because the component created on the fly and located inside GDialogRoot .

**Comment by mrFANRA** [comment]
> Hi I created a Component and It is work well, but I couldn't get my emit because the component created on the fly and located inside GDialogRoot .

Hi! Did you found solution?

**Comment by moh586** [comment]
Hi .Actually NO.I chenged the code. I just create a GDialog component and
passed a callback as props  to component and after confirm button pressed I
call the callback.

**Comment by MichaelGitArt** [comment]
@moh586 
@mrFANRA 

To receive some data from the dialog, I use such helper function.

```js

  /**
   * Run confirm dialog that returns some data
   * @param component dialog component. Should accept 'confirm' prop and run it on confirm
   * @param props any props to pass to the dialog component (except 'confirm')
   * @returns {Promise<T | null>} true if the user confirmed the dialog, null if the user canceled the dialog
   */
  const confirmWithData = async<T = any>(component: Component, props?: any): Promise<T | null> => {
    return new Promise((resolve) => {
      let confirmed = false

      $dialog.addDialog({
        component,
        props: {
          ...props,
          confirm: (data: T) => {
            confirmed = true
            resolve(data)
          },
        },

        onRemoveHook() {
          if (!confirmed) {
            resolve(null)
          }
        },
      })
    })
  }
```

Quite a simple usage without putting anything in the template.
<img width="874" alt="image" src="https://user-images.githubusercontent.com/34610289/224262591-f2447c05-4fa3-4a13-bad8-9ed68ec1d9a3.png">

Could be called even from the store with some additional modifications.
<img width="573" alt="image" src="https://user-images.githubusercontent.com/34610289/224263022-af1442f7-71f6-4054-bd80-218b49403f07.png">

<img width="863" alt="image" src="https://user-images.githubusercontent.com/34610289/224263252-94222643-1d64-498b-9b8b-d9ec0d0105c5.png">

<img width="590" alt="image" src="https://user-images.githubusercontent.com/34610289/224263683-b1554261-d0d3-4254-bdde-30f6352aebdf.png">
