### ISSUE TITLE
Default configs for all modals

### ISSUE THREAD

**Issue by mrFANRA** [gitart-group/vue-dialog#3]
Hi!

How I can add default config for all modals?

Something like this:

`
app.use(dialogPlugin,{
    'max-width':600
});
`

Thanks!

**Comment by MichaelGitArt** [comment]
Hello, @mrFANRA 
Actually, there is such logic. But it isn't mentioned in the documentation. I hope to do it soon


You need this:

`app.use(dialogPlugin,{  props: { 'max-width':600 } });`

<img width="583" alt="image" src="https://user-images.githubusercontent.com/34610289/224261517-8c0a7984-9f19-4cf4-856c-4cdb1d20275f.png">

**Comment by MichaelGitArt** [comment]
https://gitart-vue-dialog.gitart.org/guide/usage/plugin-usage.html#props

Docs is ready :)
