### ISSUE TITLE
How to get index of dialog in creation?

### ISSUE THREAD

**Issue by mrFANRA** [gitart-group/vue-dialog#4]
Hi! How to get index of dialog in creation? I want close modal programmatically,

```
let index = this.$dialog.addDialog({
        component:ModalForm,
      });
	  	  
// Somewhere in code:	  
this.$dialog.removeDialog(index);
```

I used vue-js-modal before for Vue2. This package used names in props for all modal, so I can close any modal just by name.
For examle:

```
this.$dialog.addDialog({
        component:ModalForm,
        props:{
          name:'ImName1',
        }
      });

      this.$dialog.removeDialog('ImName1');

```

With this solution and simpe custom events you package will be best in Vue3!

**Comment by MichaelGitArt** [comment]
@mrFANRA good point. Actually working with an index looks tricky now. I gonna rework it a bit. I'll notify you with changes

**Comment by mrFANRA** [comment]
> @mrFANRA good point. Actually working with an index looks tricky now. I gonna rework it a bit. I'll notify you with changes

Thanks! Check please events in vue-js-modal, it's very friendly for using,

**Comment by mrFANRA** [comment]
> Hope it helps you :) And I prefer closing dialogs from itself by emitting modelValue false. Would be nice if you will give me examples when it is not enough.

Thanks! With keys all work better!

I have first modal layer with list of models, user can edit one of them. Second modal is opening with edit form, but in first layer we still listen server for access policies. In any time we can get deny for opened form, second layer must closing automatically and starts another scenario.


One question more. I can't understand how to get data with onClose hook. 

For example in modal:
`this.$emit("update:modelValue",{hello:'World!'});`

Root component:
```
this.$dialog.addDialog({
        component:AddForm,
      }, {
        onClose: (event) => {
          console.log(...); // {hello:'World!'}
        },
      });
```

**Comment by MichaelGitArt** [comment]
@mrFANRA
update:modelValue should always emit a "false" value.

Here is a composable that I use to get some data from dialog (useDialogReturnData)
https://stackblitz.com/edit/gitart-vue-dialog-plugin-usage-bdqne3?file=src/components/composition/Launcher.vue


Launch the dialog then click on confirm or cancel the dialog. And see in the console.
