### ISSUE TITLE
Error in lazy loading component

### ISSUE THREAD

**Issue by mrFANRA** [gitart-group/vue-dialog#5]
Hi! I have error when using dynamic(lazy) component. Is it bug or my mistake?

```
const customComponent= () => import("./custom-component");

this.$dialog.addDialog({
        component:customComponent,
      });
```

Log:
[Vue warn]: Invalid VNode type: undefined (undefined)

**Comment by mrFANRA** [comment]
sorry my mistake

**Comment by MichaelGitArt** [comment]
Yes, lazy component requires defineAsyncComponent
