### ISSUE TITLE
TypeScript 5/Vue 3.3.4 Support

### ISSUE THREAD

**Issue by zacharymartens** [gitart-group/vue-dialog#7]
Hi,

I am experiencing a type check error when running `vue-tsc==1.6.5` on my project. It looks like it is caused by the latest `@vue/tsconfig/tsconfig.dom.json` which specifies `moduleResolution: "bundler"`.

This [issue](https://github.com/microsoft/TypeScript/issues/52363) seems to explain the underlying cause of the error.

The output from `vue-tsc --noEmit`:
```
Could not find a declaration file for module 'gitart-vue-dialog'. '.../node_modules/gitart-vue-dialog/dist/index.mjs' implicitly has an 'any' type.
  There are types at '.../node_modules/gitart-vue-dialog/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'gitart-vue-dialog' library may need to update its package.json or typings.
```

Thank you! This library is great.

**Comment by MichaelGitArt** [comment]
@zacharymartens Hello, and thank you for the issue. Could you please provide some minimal reproduction? Repository on github or stakblitz?

**Comment by zacharymartens** [comment]
Sure, [here](https://stackblitz.com/edit/vitejs-vite-5z7sb9) is a stackblitz based off of the default Vitejs template from their getting started page. If you open up the terminal and execute `npm run build`, you should get the previously mentioned error message during the `vue-tsc` typecheck.

The only changes made from the default template were adding the `gitart-vue-dialog` dependency to `package.json` and adding the import for it to `App.vue`.

**Comment by MichaelGitArt** [comment]
@zacharymartens Thanks, please try gitart-vue-dialog@3.1.0

**Comment by zacharymartens** [comment]
Works like a charm. Thank you for the support and quick response!
